mfvanek/pg-index-health

build.gradle
src/main/java/com/mfvanek/pg/index/maintenance/IndexMaintenanceImpl.java
src/main/resources/sql/duplicated_indexes.sql
src/main/resources/sql/foreign_keys_without_index.sql
src/main/resources/sql/indexes_with_null_values.sql
src/main/resources/sql/intersecting_indexes.sql
src/main/resources/sql/invalid_indexes.sql
src/main/resources/sql/tables_with_missing_indexes.sql
src/main/resources/sql/tables_without_primary_key.sql
src/main/resources/sql/unused_indexes.sql

Explicitly specify pg_catalog for all sql queries #10

---

src/main/java/io/github/mfvanek/pg/index/health/logger/AbstractIndexesHealthLogger.java
src/main/java/io/github/mfvanek/pg/index/health/logger/Exclusions.java
src/main/java/io/github/mfvanek/pg/index/health/logger/IndexesHealthLogger.java
src/main/java/io/github/mfvanek/pg/model/MemoryUnit.java
src/main/java/io/github/mfvanek/pg/utils/Validators.java
src/test/java/io/github/mfvanek/pg/index/health/logger/ExclusionsTest.java
src/test/java/io/github/mfvanek/pg/model/MemoryUnitTest.java

in withIndexSizeThreshold and withTableSizeThreshold methods in Exclusions.Builder
#29

Added ability to accept zero value of thresholdUnitsCount argument

---

build.gradle
src/main/java/io/github/mfvanek/pg/index/maintenance/Diagnostics.java
src/main/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenance.java
src/main/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImpl.java
src/main/java/io/github/mfvanek/pg/utils/SqlQueryReader.java
src/main/java/io/github/mfvanek/pg/utils/Validators.java
src/main/resources/sql/bloated_indexes.sql
src/main/resources/sql/bloated_tables.sql
src/test/java/io/github/mfvanek/pg/index/maintenance/DiagnosticsTest.java
src/test/java/io/github/mfvanek/pg/utils/SqlQueryReaderTest.java

Fixed monitoring for bloat under user without read privilege

---

README.md
src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthImplTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImplTest.java
src/test/java/io/github/mfvanek/pg/utils/DatabaseAwareTestBase.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java

Added tests with hash indexes

---

src/main/java/io/github/mfvanek/pg/utils/NamedParametersParser.java
src/main/java/io/github/mfvanek/pg/utils/SqlQueryReader.java
src/main/resources/sql/bloated_indexes.sql
src/main/resources/sql/bloated_tables.sql
src/main/resources/sql/duplicated_indexes.sql
src/main/resources/sql/foreign_keys_without_index.sql
src/main/resources/sql/indexes_with_null_values.sql
src/main/resources/sql/intersected_indexes.sql
src/main/resources/sql/invalid_indexes.sql
src/main/resources/sql/tables_with_missing_indexes.sql
src/main/resources/sql/tables_without_primary_key.sql
src/main/resources/sql/unused_indexes.sql
src/test/java/io/github/mfvanek/pg/utils/NamedParametersParserTest.java

Using named parameters instead of ? in sql queries.

---

README.md

Added information about using pg-index-health in unit tests.

---

src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthImplTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImplTest.java
src/test/java/io/github/mfvanek/pg/utils/DBCallback.java
src/test/java/io/github/mfvanek/pg/utils/DatabaseAwareTestBase.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java
src/test/java/io/github/mfvanek/pg/utils/TestUtils.java

Fixed false positive result on missed primary key for materialized views

---

src/main/java/io/github/mfvanek/pg/model/DuplicatedIndexes.java
src/main/java/io/github/mfvanek/pg/model/Index.java
src/main/java/io/github/mfvanek/pg/model/Table.java
src/main/java/io/github/mfvanek/pg/model/TableWithMissingIndex.java
src/test/java/io/github/mfvanek/pg/model/DuplicatedIndexesTest.java
src/test/java/io/github/mfvanek/pg/model/IndexTest.java
src/test/java/io/github/mfvanek/pg/model/IndexWithSizeTest.java
src/test/java/io/github/mfvanek/pg/model/TableTest.java
src/test/java/io/github/mfvanek/pg/model/TableWithMissingIndexTest.java

More flexible API for using in tests

---

src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthImplTest.java
src/test/java/io/github/mfvanek/pg/index/health/logger/IndexesHealthLoggerTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImplTest.java
src/test/java/io/github/mfvanek/pg/settings/ImportantParamTest.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java

Wrong detection of intersected indexes

---

src/main/java/io/github/mfvanek/pg/model/ForeignKey.java
src/main/java/io/github/mfvanek/pg/utils/Validators.java
src/test/java/io/github/mfvanek/pg/model/ForeignKeyTest.java

https://github.com/mfvanek/pg-index-health/issues/70

Add equals method to ForeignKey

---

src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthImplTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImplTest.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java

Wrong detection of Duplicated indexes with different collations

---

src/main/java/io/github/mfvanek/pg/index/health/IndexesHealth.java
src/main/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenance.java
src/main/java/io/github/mfvanek/pg/model/ForeignKey.java
src/main/java/io/github/mfvanek/pg/model/PgContext.java
src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthImplTest.java
src/test/java/io/github/mfvanek/pg/index/health/IndexesHealthMultipleSchemasTest.java
src/test/java/io/github/mfvanek/pg/index/health/logger/SimpleHealthLoggerTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceImplTest.java
src/test/java/io/github/mfvanek/pg/index/maintenance/IndexMaintenanceMultipleSchemasTest.java
src/test/java/io/github/mfvanek/pg/model/ForeignKeyTest.java
src/test/java/io/github/mfvanek/pg/model/PgContextTest.java
src/test/java/io/github/mfvanek/pg/utils/DatabaseAwareTestBase.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java

Support several PgContext in indexMaintenance.get* methods

---

src/main/java/io/github/mfvanek/pg/common/health/DatabaseHealthImpl.java
src/main/java/io/github/mfvanek/pg/common/health/ReplicasHelper.java
src/main/java/io/github/mfvanek/pg/common/maintenance/MaintenanceFactory.java
src/main/java/io/github/mfvanek/pg/common/management/DatabaseManagement.java
src/main/java/io/github/mfvanek/pg/common/management/DatabaseManagementImpl.java
src/main/java/io/github/mfvanek/pg/statistics/StatisticsAware.java
src/main/java/io/github/mfvanek/pg/statistics/maintenance/StatisticsMaintenanceOnHost.java
src/main/java/io/github/mfvanek/pg/statistics/maintenance/StatisticsMaintenanceOnHostImpl.java
src/test/java/io/github/mfvanek/pg/common/health/ReplicasHelperTest.java
src/test/java/io/github/mfvanek/pg/common/maintenance/MaintenanceFactoryImplTest.java
src/test/java/io/github/mfvanek/pg/common/management/DatabaseManagementImplTest.java
src/test/java/io/github/mfvanek/pg/statistics/maintenance/StatisticsMaintenanceOnHostImplEmptyTest.java
src/test/java/io/github/mfvanek/pg/statistics/maintenance/StatisticsMaintenanceOnHostImplTest.java
src/test/java/io/github/mfvanek/pg/utils/DatabasePopulator.java
src/test/java/io/github/mfvanek/pg/utils/PostgresVersionTest.java

Log last stat_reset timestamp

---

build.gradle
spotbugs/exclude.xml
src/main/java/io/github/mfvanek/pg/common/health/logger/Exclusions.java
src/main/java/io/github/mfvanek/pg/common/health/logger/ExclusionsBuilder.java
src/main/java/io/github/mfvanek/pg/connection/HighAvailabilityPgConnectionFactoryImpl.java
src/main/java/io/github/mfvanek/pg/connection/PgConnection.java
src/main/java/io/github/mfvanek/pg/connection/PgConnectionFactory.java
src/main/java/io/github/mfvanek/pg/connection/PgConnectionFactoryImpl.java
src/main/java/io/github/mfvanek/pg/connection/PgConnectionImpl.java
src/main/java/io/github/mfvanek/pg/connection/PgHost.java
src/main/java/io/github/mfvanek/pg/connection/PgHostImpl.java
src/main/java/io/github/mfvanek/pg/connection/PgUrlParser.java
src/main/java/io/github/mfvanek/pg/connection/PrimaryHostDeterminer.java
src/main/java/io/github/mfvanek/pg/connection/PrimaryHostDeterminerImpl.java
src/main/java/io/github/mfvanek/pg/utils/QueryExecutor.java
src/test/java/io/github/mfvanek/pg/common/health/logger/ExclusionsBuilderTest.java
src/test/java/io/github/mfvanek/pg/common/health/logger/ExclusionsTest.java
src/test/java/io/github/mfvanek/pg/connection/HighAvailabilityPgConnectionFactoryImplTest.java
src/test/java/io/github/mfvanek/pg/connection/PgConnectionImplTest.java
src/test/java/io/github/mfvanek/pg/connection/PgHostImplTest.java
src/test/java/io/github/mfvanek/pg/connection/PgUrlParserTest.java
src/test/java/io/github/mfvanek/pg/connection/PrimaryHostDeterminerImplTest.java
src/test/java/io/github/mfvanek/pg/utils/PostgresVersionTest.java
src/test/java/io/github/mfvanek/pg/utils/QueryExecutorTest.java

Do not create separate connection to the primary host

---

.github/workflows/tests.yml
README.md
build.gradle
src/test/java/io/github/mfvanek/pg/embedded/PostgresDbExtension.java
src/test/java/io/github/mfvanek/pg/utils/PostgresVersionTest.java

Added PostgreSQL 13 support and set as default version for tests and development

---

README.md

Added link to the Spring Boot Starter

---

build.gradle
src/main/java/io/github/mfvanek/pg/connection/ConnectionCredentials.java
src/main/java/io/github/mfvanek/pg/connection/PgConnectionImpl.java
src/main/java/io/github/mfvanek/pg/connection/PgHostImpl.java
src/main/java/io/github/mfvanek/pg/model/index/DuplicatedIndexes.java
src/main/java/io/github/mfvanek/pg/model/index/ForeignKey.java
src/main/java/io/github/mfvanek/pg/model/index/Index.java
src/main/java/io/github/mfvanek/pg/model/index/IndexWithBloat.java
src/main/java/io/github/mfvanek/pg/model/index/IndexWithNulls.java
src/main/java/io/github/mfvanek/pg/model/index/IndexWithSize.java
src/main/java/io/github/mfvanek/pg/model/index/UnusedIndex.java
src/main/java/io/github/mfvanek/pg/model/table/Table.java
src/main/java/io/github/mfvanek/pg/model/table/TableWithBloat.java
src/main/java/io/github/mfvanek/pg/model/table/TableWithMissingIndex.java
src/main/java/io/github/mfvanek/pg/settings/PgParamImpl.java
src/test/java/io/github/mfvanek/pg/connection/ConnectionCredentialsTest.java
src/test/java/io/github/mfvanek/pg/connection/PgConnectionImplTest.java
src/test/java/io/github/mfvanek/pg/connection/PgHostImplTest.java
src/test/java/io/github/mfvanek/pg/model/index/DuplicatedIndexesTest.java
src/test/java/io/github/mfvanek/pg/model/index/ForeignKeyTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexWithBloatTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexWithNullsTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexWithSizeTest.java
src/test/java/io/github/mfvanek/pg/model/index/UnusedIndexTest.java
src/test/java/io/github/mfvanek/pg/model/table/TableTest.java
src/test/java/io/github/mfvanek/pg/model/table/TableWithBloatTest.java
src/test/java/io/github/mfvanek/pg/model/table/TableWithMissingIndexTest.java
src/test/java/io/github/mfvanek/pg/settings/PgParamImplTest.java

According to https://www.baeldung.com/java-equals-hashcode-contracts

Equals and hashCode contracts

---

src/main/java/io/github/mfvanek/pg/generator/DbMigrationGenerator.java
src/main/java/io/github/mfvanek/pg/generator/DbMigrationGeneratorImpl.java
src/main/java/io/github/mfvanek/pg/generator/GeneratingOptions.java
src/main/java/io/github/mfvanek/pg/generator/IdxPosition.java
src/main/java/io/github/mfvanek/pg/generator/PgIdentifierNameGenerator.java
src/main/java/io/github/mfvanek/pg/generator/PgIndexOnForeignKeyGenerator.java
src/test/java/io/github/mfvanek/pg/generator/DbMigrationGeneratorImplTest.java
src/test/java/io/github/mfvanek/pg/generator/GeneratingOptionsTest.java
src/test/java/io/github/mfvanek/pg/generator/PgIdentifierNameGeneratorTest.java
src/test/java/io/github/mfvanek/pg/generator/PgIndexOnForeignKeyGeneratorTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexWithNullsTest.java

DbMigrationGenerator

---

src/test/java/io/github/mfvanek/pg/model/index/DuplicatedIndexesTest.java
src/test/java/io/github/mfvanek/pg/model/index/ForeignKeyTest.java
src/test/java/io/github/mfvanek/pg/model/index/IndexWithNullsTest.java
src/test/java/io/github/mfvanek/pg/settings/ServerSpecificationTest.java

Reorganized the lambda code to have only one call, possibly throwing an exception

---

build.gradle
src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithJsonTypeCheckOnClusterTest.java
src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithoutDescriptionCheckOnClusterTest.java
src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithJsonTypeCheckOnHostTest.java
src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithoutDescriptionCheckOnHostTest.java
src/test/java/io/github/mfvanek/pg/support/DatabasePopulator.java
src/test/java/io/github/mfvanek/pg/support/PostgreSqlContainerWrapper.java
src/test/java/io/github/mfvanek/pg/support/statements/DropColumnStatement.java

Updated sql queries. Fixed bug with dropped columns. Dropped columns case has covered with tests.

Skipping dropped columns

---

README.md
src/main/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithSerialTypesCheckOnCluster.java
src/main/java/io/github/mfvanek/pg/checks/extractors/ColumnWithSerialTypeExtractor.java
src/main/java/io/github/mfvanek/pg/checks/host/ColumnsWithSerialTypesCheckOnHost.java
src/main/java/io/github/mfvanek/pg/common/health/logger/AbstractHealthLogger.java
src/main/java/io/github/mfvanek/pg/common/health/logger/SimpleLoggingKey.java
src/main/java/io/github/mfvanek/pg/common/maintenance/DatabaseChecks.java
src/main/java/io/github/mfvanek/pg/common/maintenance/Diagnostic.java
src/main/java/io/github/mfvanek/pg/model/table/Column.java
src/main/java/io/github/mfvanek/pg/model/table/ColumnNameAware.java
src/main/java/io/github/mfvanek/pg/model/table/ColumnWithSerialType.java
src/main/java/io/github/mfvanek/pg/model/table/SerialType.java
src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithSerialTypesCheckOnClusterTest.java
src/test/java/io/github/mfvanek/pg/checks/extractors/ColumnWithSerialTypeExtractorTest.java
src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithSerialTypesCheckOnHostTest.java
src/test/java/io/github/mfvanek/pg/common/health/logger/HealthLoggerTest.java
src/test/java/io/github/mfvanek/pg/common/health/logger/StandardHealthLoggerTest.java
src/test/java/io/github/mfvanek/pg/model/table/ColumnWithSerialTypeTest.java
src/test/java/io/github/mfvanek/pg/model/table/SerialTypeTest.java
src/test/java/io/github/mfvanek/pg/support/DatabasePopulator.java
src/test/java/io/github/mfvanek/pg/support/statements/AbstractDbStatement.java
src/test/java/io/github/mfvanek/pg/support/statements/CreateTableWithColumnOfBigSerialTypeStatement.java

https://github.com/mfvanek/pg-index-health/issues/132

Do not use serial types for non primary key columns

---

.github/workflows/tests.yml
build.gradle
src/test/java/io/github/mfvanek/pg/connection/PrimaryHostDeterminerClusterTest.java
src/test/java/io/github/mfvanek/pg/support/ClusterAwareTestBase.java
src/test/java/io/github/mfvanek/pg/support/PostgreSqlContainerWrapper.java
src/test/java/io/github/mfvanek/pg/support/PostgreSqlDataSourceHelper.java
src/test/java/io/github/mfvanek/pg/support/PostgresBitnamiRepmgrContainer.java
src/test/java/io/github/mfvanek/pg/support/PostgresSqlClusterWrapper.java

add: Bitnami postgresql with repmgr container
add: Wrapper for postgresql cluster with 2 nodes
add: Test for primaryHostDeterminer on cluster
Signed-off-by: Antipin Alexey <evreke@gmail.com>

Introduce postgres cluster for tests

---

.github/workflows/tests.yml
README.md
src/test/java/io/github/mfvanek/pg/e2e/PostgresSqlClusterWrapper.java
src/test/java/io/github/mfvanek/pg/statistics/maintenance/StatisticsMaintenanceOnHostImplEmptyTest.java
src/test/java/io/github/mfvanek/pg/support/DatabaseAwareTestBase.java
src/test/java/io/github/mfvanek/pg/support/PostgreSqlContainerWrapper.java
src/test/java/io/github/mfvanek/pg/utils/PostgresVersionTest.java

Added support for PostgreSQL 15

---

build.gradle
pg-index-health-jdbc-connection/src/test/java/io/github/mfvanek/pg/connection/ConnectionCredentialsTest.java
pg-index-health-jdbc-connection/src/test/java/io/github/mfvanek/pg/connection/HighAvailabilityPgConnectionFactoryImplTest.java
pg-index-health-jdbc-connection/src/test/java/io/github/mfvanek/pg/connection/PgConnectionImplTest.java
pg-index-health-jdbc-connection/src/test/java/io/github/mfvanek/pg/connection/PgHostImplTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/column/ColumnTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/column/ColumnWithSerialTypeTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/constraint/ForeignKeyTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/function/StoredFunctionTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/DuplicatedIndexesTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/IndexTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/IndexWithBloatTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/IndexWithNullsTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/IndexWithSizeTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/UnusedIndexTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/table/TableTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/table/TableWithBloatTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/table/TableWithMissingIndexTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/settings/PgParamImplTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/utils/ClockHolder.java
pg-index-health/src/test/java/io/github/mfvanek/pg/utils/ClockHolderTest.java

Added Error Prone

---

build.gradle

Closes https://github.com/mfvanek/pg-index-health/issues/230

Added Jacoco Aggregation report

---

build.gradle

Closes https://github.com/mfvanek/pg-index-health/issues/231

Added retries for tests

---

pg-index-health-testing/src/main/java/io/github/mfvanek/pg/testing/PostgreSqlContainerWrapper.java
pg-index-health-testing/src/main/java/io/github/mfvanek/pg/testing/PostgresVersionHolder.java
pg-index-health-testing/src/test/java/io/github/mfvanek/pg/testing/PostgreSqlContainerWrapperTest.java

Blocks https://github.com/mfvanek/pg-index-health-demo/issues/65

Bug. Remove usage of internal API

---

build.gradle.kts
pg-index-health-generator/build.gradle.kts
pg-index-health-jdbc-connection/build.gradle.kts
pg-index-health-model/build.gradle.kts
pg-index-health-testing/build.gradle.kts
pg-index-health/build.gradle.kts
settings.gradle.kts

Migrated to Gradle Version Catalog. Updated pitest

---

.github/workflows/tests.yml

Relates to https://github.com/mfvanek/java-experiments/issues/83

Migrated to JDK 21 in pipeline

---

docker/docker-compose.yml
docker/local_development.md

Closes https://github.com/mfvanek/pg-index-health/issues/347

Add docker-compose file to run PostgreSQL locally

---

SECURITY.md

Relates to:
- https://github.com/mfvanek/pg-index-health/issues/364
- https://github.com/mfvanek/pg-index-health/issues/362
- https://github.com/mfvanek/pg-index-health/issues/322

Update sql queries

---

pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/column/Column.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/column/ColumnWithSerialType.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/Index.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithBloat.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithColumns.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithNulls.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithSize.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/table/Table.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/index/IndexWithColumnsTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/cluster/IndexesWithBooleanCheckOnCluster.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/IndexesWithBooleanCheckOnHost.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/AbstractHealthLogger.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/SimpleLoggingKey.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/maintenance/DatabaseChecks.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/maintenance/Diagnostic.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/IndexesWithBooleanCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/host/IndexesWithBooleanCheckOnHostTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/HealthLoggerTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/StandardHealthLoggerTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/support/DatabasePopulator.java
pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/CreateIndexWithBooleanValues.java

Relates to https://github.com/mfvanek/pg-index-health/issues/322

Add check "Do not index booleans"

---

README.md
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/pg-index-health.java-conventions.gradle.kts
pg-index-health/src/main/java/io/github/mfvanek/pg/utils/NamedParametersParser.java
pg-index-health/src/test/java/io/github/mfvanek/pg/utils/NamedParametersParserTest.java

Relates to https://github.com/mfvanek/pg-index-health/issues/364

Fix a bug with array slice

---

README.md
config/checkstyle/checkstyle.xml
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/cluster/BtreeIndexesOnArrayColumnsCheckOnCluster.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/BtreeIndexesOnArrayColumnsCheckOnHost.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/AbstractHealthLogger.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/Exclusions.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/ExclusionsBuilder.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/health/logger/SimpleLoggingKey.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/maintenance/DatabaseChecks.java
pg-index-health/src/main/java/io/github/mfvanek/pg/common/maintenance/Diagnostic.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/BtreeIndexesOnArrayColumnsCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/host/BtreeIndexesOnArrayColumnsCheckOnHostTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/ExclusionsBuilderTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/ExclusionsTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/HealthLoggerTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/common/health/logger/StandardHealthLoggerTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/support/DatabasePopulator.java
pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/CreateIndexesOnArrayColumn.java

Relates to https://github.com/mfvanek/pg-index-health/issues/364

Added check for b-tree indexes on array columns

---

README.md
build.gradle.kts

Relates to https://github.com/mfvanek/pg-index-health/issues/384

Next development iteration

---

CONTRIBUTING.md
README.md

Closes https://github.com/mfvanek/pg-index-health/issues/405

Add check type to the README.md

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/AbstractCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/BtreeIndexesOnArrayColumnsCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/ColumnsWithJsonTypeCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/ColumnsWithSerialTypesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/ColumnsWithoutDescriptionCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/DuplicatedForeignKeysCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/DuplicatedIndexesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/ForeignKeysNotCoveredWithIndexCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/FunctionsWithoutDescriptionCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/IndexesWithBloatCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/IndexesWithBooleanCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/IndexesWithNullValuesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/IntersectedForeignKeysCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/IntersectedIndexesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/InvalidIndexesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/NotValidConstraintsCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/PrimaryKeysWithSerialTypesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/SequenceOverflowCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/TablesWithBloatCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/TablesWithMissingIndexesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/TablesWithoutDescriptionCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/TablesWithoutPrimaryKeyCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/host/UnusedIndexesCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/common/maintenance/DatabaseCheckOnHost.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithJsonTypeCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithoutDescriptionCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/support/AbstractCheckOnHostAssert.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/cluster/AbstractCheckOnCluster.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithJsonTypeCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithoutDescriptionCheckOnClusterTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/454

Add ability to filter out results on host

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/common/maintenance/DatabaseCheckOnHost.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/AbstractCheckOnHostTest.java
spring-boot-integration/kotlin-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/PostgresDemoApplicationKtTest.kt
spring-boot-integration/postgres-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/PostgresDemoApplicationTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/479

Extend DatabaseCheckOnHost with overloaded method for public schema with predicate

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/common/maintenance/Diagnostic.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/common/maintenance/DiagnosticTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/483

Consider to add an overloaded constructors to Diagnostic class

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/checks/extractors/ColumnWithSerialTypeExtractor.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/ColumnsWithSerialTypesCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/PrimaryKeysWithSerialTypesCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/SequenceOverflowCheckOnHostTest.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/PgContext.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/column/ColumnWithSerialType.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/AbstractSkipTablesPredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipDbObjectsByNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/sequence/SequenceNameAware.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/sequence/SequenceState.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/AbstractSkipTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipFlywayTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipLiquibaseTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipTablesByNamePredicateTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/ColumnsWithSerialTypesCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/PrimaryKeysWithSerialTypesCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/SequenceOverflowCheckOnClusterTest.java

Relates to https://github.com/mfvanek/pg-index-health/issues/462

Add SkipBySequenceNamePredicate

---

pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/IndexesWithBloatCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/IndexesWithBooleanCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/IndexesWithNullValuesCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/InvalidIndexesCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/UnusedIndexesCheckOnHostTest.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/AbstractSkipTablesPredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipDbObjectsByNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipIndexesByNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipTablesByNamePredicate.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/AbstractSkipTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipIndexesByNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipTablesByNamePredicateTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/predicates/FilterIndexesByNamePredicate.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/IndexesWithBloatCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/IndexesWithBooleanCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/IndexesWithNullValuesCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/InvalidIndexesCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/UnusedIndexesCheckOnClusterTest.java

Relates to https://github.com/mfvanek/pg-index-health/issues/462

Add SkipIndexesByNamePredicate

---

config/checkstyle/checkstyle.xml
pg-index-health-core/src/test/java/io/github/mfvanek/pg/checks/host/IndexesWithBloatCheckOnHostTest.java
pg-index-health-logger/src/main/java/io/github/mfvanek/pg/common/health/logger/AbstractHealthLogger.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithColumns.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipSmallIndexesPredicate.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipSmallIndexesPredicateTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/checks/predicates/FilterIndexesBySizePredicate.java
pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/IndexesWithBloatCheckOnClusterTest.java

Relates to https://github.com/mfvanek/pg-index-health/issues/462

Add SkipSmallIndexesPredicate

---

pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/constraint/DuplicatedForeignKeys.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/constraint/ForeignKey.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/context/PgContext.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/function/StoredFunction.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/DuplicatedIndexes.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/index/IndexWithBloat.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/sequence/SequenceState.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/table/Table.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/table/TableWithBloat.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/table/TableWithMissingIndex.java

Closes https://github.com/mfvanek/pg-index-health/issues/482

Final model classes

---

buildSrc/src/main/kotlin/pg-index-health.java-conventions.gradle.kts

Closes https://github.com/mfvanek/pg-index-health/issues/503

Fix cross-links in javadoc

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/pg-index-health.kotlin-application.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
spring-boot-integration/kotlin-custom-ds-demo-app/build.gradle.kts
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/PostgresCustomDataSourceDemoApplication.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/config/DataSourceConfiguration.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/resources/application.yaml
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/resources/changelog/changelog.yaml
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/resources/changelog/sql/warehouse.sql
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/resources/init.sql
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/PostgresCustomDataSourceDemoApplicationKtRunTest.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/PostgresCustomDataSourceDemoApplicationKtTest.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/resources/application-test.yaml
spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfiguration.java
spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthCondition.java
spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthProperties.java
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/AutoConfigurationTestBase.java
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfigurationTest.java
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthPropertiesTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/521

Add ability to customize name of dataSource bean and databaseUrl

---

README.md
spring-boot-integration/h2-demo-app/src/test/java/io/github/mfvanek/pg/spring/h2/H2DemoApplicationTest.java
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/DatabaseStructureStaticAnalysisTest.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/PostgresCustomDataSourceDemoApplicationKtRunTest.kt
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/PostgresCustomDataSourceDemoApplicationKtTest.kt
spring-boot-integration/kotlin-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/DatabaseStructureStaticAnalysisTest.kt
spring-boot-integration/kotlin-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/PostgresDemoApplicationKtTest.kt
spring-boot-integration/postgres-demo-app-with-custom-user/src/test/java/io/github/mfvanek/pg/spring/postgres/with/custom/user/DatabaseStructureStaticAnalysisTest.java
spring-boot-integration/postgres-demo-app-with-custom-user/src/test/java/io/github/mfvanek/pg/spring/postgres/with/custom/user/PostgresWithCustomUserDemoApplicationTest.java
spring-boot-integration/postgres-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/DatabaseStructureStaticAnalysisTest.java
spring-boot-integration/postgres-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/PostgresDemoApplicationTest.java
spring-boot-integration/postgres-tc-url-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/tc/url/DatabaseStructureStaticAnalysisTest.java
spring-boot-integration/postgres-tc-url-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/tc/url/PostgresTestcontainersUrlDemoApplicationTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/532

Describe the main idea in readme or contribution guide

---

pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/checks/host/NotValidConstraintsCheckOnHostTest.java
pg-index-health-core/src/testFixtures/java/io/github/mfvanek/pg/core/fixtures/support/statements/CreateBadlyNamedObjectsStatement.java
pg-index-health-logger/src/test/java/io/github/mfvanek/pg/health/logger/HealthLoggerTest.java
pg-index-health-logger/src/test/java/io/github/mfvanek/pg/health/logger/StandardHealthLoggerTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/health/checks/cluster/NotValidConstraintsCheckOnClusterTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/605

[not_valid_constraints] Add test with badly named constraints

---

CONTRIBUTING.md

Closes https://github.com/mfvanek/pg-index-health/issues/614

Extend CONTRIBUTING.md and describe operations with git submodule

---

README.md
doc/rus/indexes_with_unnecessary_where_clause.md
doc/rus/primary_keys_with_varchar.md
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/common/Diagnostic.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/host/IndexesWithUnnecessaryWhereClauseCheckOnHost.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/checks/host/IndexesWithUnnecessaryWhereClauseCheckOnHostTest.java
pg-index-health-core/src/testFixtures/java/io/github/mfvanek/pg/core/fixtures/support/DatabasePopulator.java
pg-index-health-core/src/testFixtures/java/io/github/mfvanek/pg/core/fixtures/support/statements/CreateIndexWithUnnecessaryWhereClauseStatement.java
pg-index-health-core/src/testFixtures/java/io/github/mfvanek/pg/core/fixtures/support/statements/CreatePartitionedIndexWithUnnecessaryWhereClauseStatement.java
pg-index-health-core/src/testFixtures/java/io/github/mfvanek/pg/core/fixtures/support/statements/CreateTableWithFixedLengthVarcharStatement.java
pg-index-health-logger/src/main/java/io/github/mfvanek/pg/health/logger/DatabaseChecksOnCluster.java
pg-index-health-logger/src/test/java/io/github/mfvanek/pg/health/logger/HealthLoggerTest.java
pg-index-health-logger/src/test/java/io/github/mfvanek/pg/health/logger/HealthLoggerTestBase.java
pg-index-health-logger/src/test/java/io/github/mfvanek/pg/health/logger/StandardHealthLoggerTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/health/checks/cluster/IndexesWithUnnecessaryWhereClauseCheckOnCluster.java
pg-index-health/src/test/java/io/github/mfvanek/pg/health/checks/cluster/IndexesWithUnnecessaryWhereClauseCheckOnClusterTest.java
spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureChecksAutoConfiguration.java
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/AutoConfigurationTestBase.java
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfigurationFilteringTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/194

Add a check to prevent unnecessary where-clauses in index creating queries on not null columns 

---

CONTRIBUTING.md

Relates to https://github.com/mfvanek/pg-index-health/issues/574

Need to have Docker

---

.github/workflows/tests.yml
CONTRIBUTING.md
docker/docker-compose.yml
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/utils/PostgresVersionTest.java
pg-index-health-jdbc-connection/src/test/java/io/github/mfvanek/pg/connection/PgConnectionImplTest.java
pg-index-health-testing/src/main/java/io/github/mfvanek/pg/testing/PostgreSqlContainerWrapper.java
pg-index-health-testing/src/main/java/io/github/mfvanek/pg/testing/PostgresVersionHolder.java
pg-index-health-testing/src/test/java/io/github/mfvanek/pg/testing/PostgreSqlClusterWrapperTest.java
pg-index-health-testing/src/test/java/io/github/mfvanek/pg/testing/PostgreSqlContainerWrapperTest.java
pg-index-health-testing/src/test/java/io/github/mfvanek/pg/testing/PostgresVersionHolderTest.java
spring-boot-integration/kotlin-custom-ds-demo-app/src/main/resources/application.yaml
spring-boot-integration/pg-index-health-test-starter/src/test/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfigurationTest.java
spring-boot-integration/postgres-tc-url-demo-app/src/main/resources/application.yaml
spring-boot-integration/postgres-tc-url-demo-app/src/test/java/io/github/mfvanek/pg/spring/postgres/tc/url/PostgresTestcontainersUrlDemoApplicationTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/618

Update PostgreSQL in tests and CI

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/common/DatabaseCheckOnHost.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/checks/host/AbstractCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/checks/host/ColumnsWithSerialTypesCheckOnHostTest.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/utils/QueryExecutorsTest.java
pg-index-health-logger/src/main/java/io/github/mfvanek/pg/health/logger/HealthLogger.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/column/ColumnWithSerialType.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/constraint/ForeignKey.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/context/PgContext.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipFlywayTablesPredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipIndexesByNamePredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipLiquibaseTablesPredicate.java
pg-index-health-model/src/main/java/io/github/mfvanek/pg/model/predicates/SkipTablesByNamePredicate.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/column/ColumnWithSerialTypeTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/context/PgContextTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/AbstractSkipTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipBySequenceNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipFlywayTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipIndexesByNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipLiquibaseTablesPredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/predicates/SkipTablesByNamePredicateTest.java
pg-index-health-model/src/test/java/io/github/mfvanek/pg/model/table/TableTest.java
pg-index-health/src/main/java/io/github/mfvanek/pg/health/checks/common/DatabaseCheckOnCluster.java
pg-index-health/src/test/java/io/github/mfvanek/pg/health/checks/cluster/AbstractCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/health/checks/cluster/ColumnsWithSerialTypesCheckOnClusterTest.java
pg-index-health/src/test/java/io/github/mfvanek/pg/health/checks/common/DatabaseCheckOnClusterTest.java
spring-boot-integration/kotlin-custom-ds-demo-app/src/test/kotlin/io/github/mfvanek/pg/spring/postgres/kt/custom/ds/DatabaseStructureStaticAnalysisTest.kt

Closes https://github.com/mfvanek/pg-index-health/issues/542

Rename all ofPublic methods to ofDefault

---

pg-index-health-generator/src/main/java/io/github/mfvanek/pg/generator/GeneratingOptions.java
pg-index-health-generator/src/test/java/io/github/mfvanek/pg/generator/GeneratingOptionsTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/651

Rework builder in GeneratingOptions

---

buildSrc/src/main/kotlin/pg-index-health.pitest.gradle.kts
gradle/libs.versions.toml
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/host/AbstractCheckOnHost.java
pg-index-health/src/main/java/io/github/mfvanek/pg/health/checks/cluster/TablesWithMissingIndexesCheckOnCluster.java
pg-index-health/src/main/java/io/github/mfvanek/pg/health/checks/common/DatabaseCheckOnCluster.java

Closes https://github.com/mfvanek/pg-index-health/issues/639

Update EqualsVerifier to 4.x

---

pg-index-health-generator/src/main/java/io/github/mfvanek/pg/generator/AbstractDbMigrationGenerator.java
pg-index-health-generator/src/main/java/io/github/mfvanek/pg/generator/ColumnWithSerialTypeMigrationGenerator.java
pg-index-health-generator/src/main/java/io/github/mfvanek/pg/generator/ForeignKeyMigrationGenerator.java
pg-index-health-generator/src/test/java/io/github/mfvanek/pg/generator/ForeignKeyMigrationGeneratorTest.java

Closes https://github.com/mfvanek/pg-index-health/issues/497

Migration generator. Try to handle duplicated objects

---

README.md
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/pg-index-health.java-compilation.gradle.kts
buildSrc/src/main/kotlin/pg-index-health.java-library.gradle.kts
buildSrc/src/main/kotlin/pg-index-health.publish.gradle.kts
gradle/libs.versions.toml
pg-index-health-bom/build.gradle.kts

Closes https://github.com/mfvanek/pg-index-health/issues/661

Migrate to gradle-maven-publish-plugin

---

buildSrc/src/main/kotlin/pg-index-health.publish.gradle.kts

Closes https://github.com/mfvanek/pg-index-health/issues/660

OSSRH Migration

---

buildSrc/src/main/kotlin/pg-index-health.kotlin-application.gradle.kts
config/detekt/detekt.yml

Closes https://github.com/mfvanek/pg-index-health/issues/691

Add new rules to detekt

---

pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/common/CheckInfo.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/common/Diagnostic.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/checks/host/AbstractCheckOnHost.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/utils/NamedParametersParser.java
pg-index-health-core/src/main/java/io/github/mfvanek/pg/core/utils/SqlQueryReader.java
pg-index-health-core/src/test/java/io/github/mfvanek/pg/core/checks/common/DiagnosticTest.java

Relates to https://github.com/mfvanek/pg-index-health/issues/708

CheckInfo should provide an SQL query
